FROM tomcat:7.0-jdk8

RUN rm -rf /usr/local/tomcat/ROOT/ /usr/local/tomcat/docs/ /usr/local/tomcat/examples /usr/local/tomcat/host-manager/ /usr/local/tomcat/ROOT/manager

#COPY tmp/server.xml /usr/local/tomcat/conf/server.xml




